IndependentWork/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'labs#index'

  resources :labs

  get '/labs/:id/mark', to: 'labs#mark', as: 'mark_lab'

  post '/labs/:id/mark', to: 'labs#grade'
end

IndependentWork/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

IndependentWork/app/models/lab.rb
class Lab < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 250 }
end

IndependentWork/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :labs

  validates :first_name, presence: true, length: { maximum: 100 }
  validates :last_name, presence: true, length: { maximum: 100 }
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
end

IndependentWork/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include ErrorHandling
end

IndependentWork/app/controllers/concerns/error_handling.rb
module ErrorHandling
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

IndependentWork/app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :find_lab, only: %i[show update destroy edit mark grade]

  def index
    @labs = Lab.all
  end

  def show
  end

  def new
    @lab = Lab.new
  end

  def create
    @lab = Lab.new(lab_params)
    @lab.user_id = 1

    if @lab.save
      redirect_to root_url
      flash[:success] = "Lab was created successfully"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if (@lab.update(lab_params))
      redirect_to root_url
      flash[:success] = "Lab was updated successfully"
    else
      render 'edit'
    end
  end

  def mark
  end

  def grade
    if (@lab.update(params.permit(:grade)))
      redirect_to root_url
      flash[:success] = "Mark was added successfully"
    else
      render 'mark'
    end
  end

  def destroy
    @lab.destroy

    redirect_to action: :index
    flash[:success] = "Lab was deleted successfully"
  end

  private

  def find_lab
    @lab = Lab.find params[:id]
  end

  def lab_params
    params.require(:lab).permit(:title, :description)
  end
end

IndependentWork/app/helpers/application_helper.rb
module ApplicationHelper
end

IndependentWork/app/helpers/labs_helper.rb
module LabsHelper
end

IndependentWork/app/views/labs/_form.html.erb
<%= form_with model: @lab do |f|%>
  <% if @lab.errors.any?%>
    <% @lab.errors.full_messages.each do |msg|%>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <h4>Title</h4>
    <%= f.text_field :title, required: true%><br>

  <h4>Description</h4>
    <%= f.text_area :description, {:class => 'form-control'}%><br>

    <%= f.submit({:class => 'btn btn-success'}) %>
    <button type="button" class="btn btn-secondary"><%= link_to "Back", root_path%></button>
<% end %>

IndependentWork/app/views/labs/edit.html.erb
<h2>Editing new lab</h2><br>

<%= render 'form' %>

IndependentWork/app/views/labs/index.html.erb
<h1>All Labs</h1><br>

<button type="button" class="btn btn-outline-primary"><%= link_to "Upload new lab", new_lab_path%></button><br><br>

<% flash.each do |type, msg| %>
  <div class="alert alert-<%= type %>">
    <%= msg %>
  </div>
<% end %>

<table class="table">
  <thead>
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Grade</th>
  </thead>

  <tbody>
    <% @labs.each do |lab| %>
      <tr>
        <td><%= lab.title %></td>
        <td><%= lab.description %></td>
        <td><%= lab.grade %></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to "Edit", edit_lab_path(lab) %></button></td>
        <td><button type="button" class="btn btn-outline-secondary"><%= link_to "Show", lab_path(lab) %></button></td>
        <td><button type="button" class="btn btn-outline-warning"><%= link_to "Add mark", mark_lab_path(lab) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to "Delete", lab_path(lab), method: :delete, data: {confirm: "Are you sure?"} %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

IndependentWork/app/views/labs/mark.html.erb
<h2>Adding mark</h2><br>

<%= form_with url: mark_lab_path(@lab) do |f| %>
  <% if @lab.errors.any?%>
    <% @lab.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger"><%= msg %></div>
    <% end %>
  <% end %>

  <h4>Grade</h4>
    <%= f.text_field :grade, {:class => 'form-control'} %><br>

    <%= f.submit({:class => 'btn btn-success'}) %>
    <button type="button" class="btn btn-secondary"><%= link_to "Back", root_path %></button>
<% end %>

IndependentWork/app/views/labs/new.html.erb
<h2>Adding new lab</h2><br>

<%= render 'form' %>

IndependentWork/app/views/labs/show.html.erb
<h1>Title: <%= @lab.title %></h1><br>
<h2>Description: <%= @lab.description %></h2><br>
<h2>Grade: <%= @lab.grade %></h2><br>
<button type="button" class="btn btn-primary"><%= link_to "Edit", edit_lab_path(@lab) %></button>
<button type="button" class="btn btn-secondary"><%= link_to "Back", labs_path %></button>
<button type="button" class="btn btn-warning"><%= link_to "Add mark", mark_lab_path %></button>

IndependentWork/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Labs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      a {
       text-decoration: none;
       color: black
      }
   </style>
  </head>

  <body>
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>